apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    zone: dev
    version: v1
spec:
  containers:
  - name: hello-world-cntr
    image: mradulpandey001/hello-world:latest
    ports:
    - containerPort: 8080
