apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world-pod-rc
spec:
  replicas: 3
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-cntr
        image: mradulpandey001/hello-world:latest
        ports:
        - containerPort: 8080
